/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserPagesView': RouteRecordInfo<'/admin/AdminUserPagesView', '/admin/AdminUserPagesView', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/components/CalendarEvents': RouteRecordInfo<'/admin/components/CalendarEvents', '/admin/components/CalendarEvents', Record<never, never>, Record<never, never>>,
    '/admin/components/DashboardCardWidget': RouteRecordInfo<'/admin/components/DashboardCardWidget', '/admin/components/DashboardCardWidget', Record<never, never>, Record<never, never>>,
    '/admin/components/EventsManagementTable': RouteRecordInfo<'/admin/components/EventsManagementTable', '/admin/components/EventsManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/EventsView': RouteRecordInfo<'/admin/EventsView', '/admin/EventsView', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/myAccounts/MyClearanceView': RouteRecordInfo<'/myAccounts/MyClearanceView', '/myAccounts/MyClearanceView', Record<never, never>, Record<never, never>>,
    '/myAccounts/MyEventsView': RouteRecordInfo<'/myAccounts/MyEventsView', '/myAccounts/MyEventsView', Record<never, never>, Record<never, never>>,
    '/myOrganization/MembersView': RouteRecordInfo<'/myOrganization/MembersView', '/myOrganization/MembersView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/students/StudentCalendar': RouteRecordInfo<'/students/StudentCalendar', '/students/StudentCalendar', Record<never, never>, Record<never, never>>,
  }
}
